import { SCGNode, EdgeType } from './graph';

/** Types of search result matches */
export enum SearchResultType {
  FUNCTION = 'function',
  CLASS = 'class',
  INTERFACE = 'interface',
  SNIPPET = 'snippet',
  FILE = 'file',
}

/** Graph context attached to search results */
export interface GraphContextInfo {
  node: SCGNode;
  relationship: EdgeType;
  distance: number;
}

/** A single search result enriched with graph context */
export interface SearchResult {
  /** Unique ID for this result */
  id: string;
  /** The matching code snippet content */
  content: string;
  /** Relevance score from vector search (0-1) */
  relevanceScore: number;
  /** Source file path */
  file: string;
  /** Line range in the source file */
  lineRange: { start: number; end: number };
  /** The matching graph node, if any */
  graphNodeId: string | null;
  /** Graph context: related nodes (callers, callees, dependencies) */
  graphContext: GraphContextInfo[];
  /** Semantic type of the match */
  matchType: SearchResultType;
  /** Snippet summary generated by LLM */
  summary: string;
}

/** Search query with metadata */
export interface SearchQuery {
  /** The natural language query string */
  text: string;
  /** Maximum results to return */
  limit: number;
  /** Minimum relevance score threshold */
  minScore: number;
  /** Optional file path filter */
  fileFilter?: string;
  /** Optional node type filter */
  typeFilter?: SearchResultType;
  /** Whether to include graph context enrichment */
  includeGraphContext: boolean;
}

/** Complete search response */
export interface SearchResponse {
  query: string;
  results: SearchResult[];
  totalMatches: number;
  searchTimeMs: number;
  graphNodesExplored: number;
  /** Warning message if search exceeded time budget */
  warning?: string;
}

/** State of the search widget */
export interface SearchState {
  query: string;
  results: SearchResult[];
  isSearching: boolean;
  error: string | null;
  selectedIndex: number;
  graphContextExpanded: boolean;
}

/** Links a search result to graph operations and other features */
export interface SearchGraphLink {
  searchResultId: string;
  graphNodeId: string;
  /** Opens GraphExplorer focused on this node */
  openInGraphExplorer: () => void;
  /** Opens ImpactAnalysis seeded from this node */
  showImpact: () => void;
  /** Opens Chat with context about this node */
  discussInChat: () => void;
}
